version: '3'

services:
  db:
    container_name: postgres-dev
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: db-dev
    ports:
      - 5432:5432
