name: Check Linting

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: Running ESLint
    timeout-minutes: 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Running Eslint
        run: yarn lint
