name: Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: Running Tests
    timeout-minutes: 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Start Container, migrate and seed
        run: yarn dev:startdb
        env:
          DATABASE_URL: 'postgresql://postgres:test@localhost:6500/nourishdb-dev'

      - name: Run tests
        run: yarn test

      - name: Stop Container
        run: yarn db:dockerdown
